### ISSUE TITLE
csv_upload

### ISSUE THREAD

**Issue by TAWinterton2** [TAWinterton2/CS-F600-ML-GUI#12]
**csv_upload**
A student should be able to upload a csv file to the server so that they can use their own data for the ML model

**Comment by raelewis** [comment]
User can successfully upload a csv file. The server will display the correct csv contents to the front end for the user. The program also saves the 'original dataset' to be displayed at any time.

**Comment by TAWinterton2** [comment]
task validation completed, closing issue.
