### ISSUE TITLE
zip_unpack

### ISSUE THREAD

**Issue by TAWinterton2** [TAWinterton2/CS-F600-ML-GUI#13]
`zip_unpack`

A student should be able to upload a zip file to the server so that they can use multiple, similarly structured datasets for the ML model.

> - [x] Given a student submitting a zip file, and the zip file contains csv files with different column names, then the student should expect an error message explaining what went wrong.
> 
> - [x] Given a student submitting a zip file, and the zip file contains more than just csv files, then the student should expect an error message explaining what went wrong. 
> 
> - [x] Given a student submitting a zip file, and the zip file contains only csv files with the same column names, then the student should be able to select the XY columns and continue. 
> 
> - [x] Given a student submitting a zip file, and an unknown exception occurs, the student should be given an error message.
>

**Comment by raelewis** [comment]
How will allowing the user to upload multiple csvs affect the front end display?

**Comment by TAWinterton2** [comment]
Python includes a library that handles zip files
 

> Documentation for Library: [](https://docs.python.org/3/library/zipfile.html)

as far as displaying on the front end. One approach I was thinking of is that when we extract the contents of a zip file, we can display all of the csv files in the form of a drop down form that the user can select from, or simply list out all csv contents in a list, and have a radio button next to each one for the user to check

**Comment by TAWinterton2** [comment]
Created a copy of the zip_unpack function indpependent of the webiste backend. It can create a "temp" folder and extract the contents of the zip folder into the temp folder. 

Just need to intergrate the function into the backend

**Comment by TAWinterton2** [comment]
module validated and merged. closing issue
