### ISSUE TITLE
Module Diagrams

### ISSUE THREAD

**Issue by raelewis** [TAWinterton2/CS-F600-ML-GUI#24]
Design the modules for your backend. The entire implementation should be visible as a modular design. Each module must have four components as follows: **Module Name**, **Module Description**, I**nput to the Module**, and **Output from the Module**. Every module should be a collection of function. Each function must have four components as follows: **Function Name**, **Function Description**, **Input to the Function**, **Output from the Function**.

**Comment by TAWinterton2** [comment]
All module functions have been completed, working on adding descriptions for each module

**Comment by TAWinterton2** [comment]
Updated Modules to have Module name, description, inputs and outputs. 

Task is ready for review

**Comment by TAWinterton2** [comment]
First path of module diagram completed. Closing issue
