### ISSUE TITLE
display_graph

### ISSUE THREAD

**Issue by raelewis** [TAWinterton2/CS-F600-ML-GUI#25]
`display_graph`

> - [x]  A student should be able to visualize the values of the model so that they can easily review their results for each step.

**Comment by raelewis** [comment]
I created a js file to store our chartjs code for displaying graphs based on dataframe values. All that's left is to update the rest of the html to call this script with the proper data.

**Comment by TAWinterton2** [comment]
feature implemented and merged into dev branch. closing issue
