### ISSUE TITLE
text_input_parse

### ISSUE THREAD

**Issue by raelewis** [TAWinterton2/CS-F600-ML-GUI#28]
This module should take in a string object, parse it's contents and extract all integers/floats from it. This function should also ensure that security is maintained while accepting text input.

**Comment by raelewis** [comment]
A simple function matching this name exists in the code, accepting a string and returning either a float, int, or ValueError. It would be better to have full form validation so we can properly prompt the user with what inputs are allowed.

**Comment by TAWinterton2** [comment]
function works and is merged into dev branch. closing issue
