### ISSUE TITLE
Modularized Code: Passthrough #1

### ISSUE THREAD

**Issue by TAWinterton2** [TAWinterton2/CS-F600-ML-GUI#52]
Review our current code and look for lines of code that can be compartmentalized into dedicated functions that we can call throughout main app.py

**Comment by raelewis** [comment]
Split up upload form's function a bit more to make it a bit easier to follow validation/other functionality.

**Comment by raelewis** [comment]
Inheritance class has been added for machine learning models.

**Comment by TAWinterton2** [comment]
First passthrough of code is done. Marking as complete
