### ISSUE TITLE
Unit Test Plan / Testing Plan (Linear Regression)

### ISSUE THREAD

**Issue by raelewis** [TAWinterton2/CS-F600-ML-GUI#55]
Design a unit test plan for your software. Specifically mention the test cases. Each unit test case must have three components as follows:  **Function Name**, **Input to the Function**, **Expected Output from the Function**.

**Comment by raelewis** [comment]
Initial draft of testing plan has been created and shared with classmates.

**Comment by TAWinterton2** [comment]
Testing completed for linear regression completed. Closing issue
