### ISSUE TITLE
Fix Form Locks

### ISSUE THREAD

**Issue by raelewis** [TAWinterton2/CS-F600-ML-GUI#58]
- [ ] Add limits in the javascript to prevent a user from viewing steps after the current step.
- [x] Add limit in the javascript/html to prevent a user from accidentally restart the form. Flask will not save a file upload after a form submission, so if the user attempts to backtrack to Step 1, the program should either display column selection OR be inaccessible.

**Comment by TAWinterton2** [comment]
issue was not fixed by time of final deployment, closing issue as not planned
