### ISSUE TITLE
Linear regression Home page

### ISSUE THREAD

**Issue by jbonda** [TAWinterton2/CS-F600-ML-GUI#61]
LInear regression page: User is lead to the "ml_form.html" page. But its not lead the user to ML form page URL.

**Comment by TAWinterton2** [comment]
Will update the html names to add better clarity to website pathing

**Comment by jbonda** [comment]
Perfect! Now Linear Regression leads to the Linear Regression webpage. Thank you.

**Comment by TAWinterton2** [comment]
Patch 1 Successful Merge. Closing issue.
