### ISSUE TITLE
Empty training and testing

### ISSUE THREAD

**Issue by jbonda** [TAWinterton2/CS-F600-ML-GUI#63]
Training: ""
Testing: ""
Nothing selected in both the options should generate an appropriate error message.
`invalid literal for int() with base 10: "
`

**Comment by TAWinterton2** [comment]
It appears that it currently throws the default error provided by text_input_parse() when an empty string is passed. Will update Error handling to throw a more clearer error to the user.

**Comment by TAWinterton2** [comment]
Updated error handling in text_input_prase() to throw a more appropriate error message to the user. Issue is ready for review.

**Comment by jbonda** [comment]
Update/specify the testing branch for this.

**Comment by raelewis** [comment]
Moved the fix onto new branch located #71 . This contains the fix mentioned here as well as those found in #70 .

**Comment by TAWinterton2** [comment]
Patch 1 Successful Merge. Closing issue.
