### ISSUE TITLE
Integer Input: Incorrect Value

### ISSUE THREAD

**Issue by TechSolomon** [TAWinterton2/CS-F600-ML-GUI#64]
### Steps

1. Set `Max Iteration` to -1000.
2. Avoid clicking `Hyperparams` → click next.

### Error
`The 'alpha' parameter of SGDRegressor must be a float in the range [0.0, inf). Got <class 'Exception'> instead.`

**Comment by TAWinterton2** [comment]
When trying to follow your steps to replicate the error, the error we get is a default error for trying to fit the model that doesn't exist:
`'NoneType' object has no attribute 'fit'`.

We believe that both of these errors relate to the user tying to skip the skip the hyperparms part of the form. 
Will look into ways to prevent users from skipping hyperparams w/out skipping entering hyperparam values

**Comment by TAWinterton2** [comment]
While we are looking into form locking in javascript.
In the meantime, we updated the error handling so it now throws a more appropriate error message to the user instead of the default python error.

**Comment by TechSolomon** [comment]
Branch `Issue-64-Inccorrect-Value` should include the updated fixes from #70.

- https://support.atlassian.com/bitbucket-cloud/docs/git-fast-forwards-and-branch-management/

**Comment by raelewis** [comment]
Moved the fix onto new branch located #71 . This contains the fix mentioned here as well as those found in #70 .

**Comment by TAWinterton2** [comment]
Patch 1 Successful Merge. Closing issue.
