### ISSUE TITLE
`/tmp` file directory + zip file

### ISSUE THREAD

**Issue by jbonda** [TAWinterton2/CS-F600-ML-GUI#65]
Multiple zip files are saved to the Project repository and are not removed after the task has been completed.

**Comment by raelewis** [comment]
Thanks for catching this! A previous version of this code utilized a temporary file directory to save the zip files for unpacking. It would then remove these files once the process is done. It appears we missed the initial code that saves the file when we changed how we unpacked zips. We'll go through our project and make sure to remove this in the next update.

**Comment by TAWinterton2** [comment]
Patch 1 Successful merged. Closing this issue.
