### ISSUE TITLE
Beta-Testing-#2

### ISSUE THREAD

**Issue by TAWinterton2** [TAWinterton2/CS-F600-ML-GUI#75]
- [x] - specify creating name and python version for anaconda environment installation (-n and -python)
- [x] - Specify install instructions for packages/Dependinces using conda
- [x] - Swap places of training / testing tables in train_test split?
- [x] #74 - Implement filesize limits (>= 5MB )
- [x] #74 - TypeError for csv files that don't have strictly integer values.
- [x] - Flip Normalize and Standardize in description box in Normalize Data form step. 
- [x] - Handling integer input w/ spaces

**Comment by TAWinterton2** [comment]
Updated README.md to specify creating a name for your conda virtual enviroment

**Comment by TAWinterton2** [comment]
Created branch `demo-test-fixes` for this issue

**Comment by TAWinterton2** [comment]
Added installation instructions for dependences using conda

**Comment by raelewis** [comment]
-Fixes for this issue can be found in the linked pull request.

**Comment by TAWinterton2** [comment]
Fixes implemented, closing issue
