### ISSUE TITLE
User sessions are not independent like initially thought.

### ISSUE THREAD

**Issue by raelewis** [TAWinterton2/CS-F600-ML-GUI#78]
Issue regarding multiple instances/tabs/users of the project having access to each other's files or other session-specific related items. Project works for a single user progressing through each step, but encounters errors with regards to file uploads being shared/the program remembering the most recent file upload in the data snapshot.

**Comment by raelewis** [comment]
Reviewing [Flask Session](https://flask-session.readthedocs.io/en/latest/index.html), it appears to allow the use of cookies to denote individual users. Attempting to convert our data snapshot directly into this session object will not work for larger files due to cookie size limitations. We may need to restructure slightly to create a small database to store user specific items. Alternatively, we'll need to store user files for the duration of the process so we can use them for each step.

**Comment by TAWinterton2** [comment]
Issue was not able to be fix by time of final deployment, closing issue not as planned
