### ISSUE TITLE
Deployment testing

### ISSUE THREAD

**Issue by TAWinterton2** [TAWinterton2/CS-F600-ML-GUI#79]
- [x] - Timeout Error Handling (Related to #75 #74   for uploading large .csv files or .zip files)
- [x] - No closing remarks on issue (Other team must check patch before merge and close)
- [x] - Table Headers in Evaluation Data should have hyperlink to SciKit documentation 
- [x] - ~~Form Lock Training Testing Split, Disable next button. (Invalid input is allowing user to go to the next step).~~
- [x] - Rename "Submit Hyperparameters" to "Check Hyperparameters" or "Validate Hyperparameters"

**Comment by TAWinterton2** [comment]
Added in file size limits to help eliminate large file sizes causing larger server load

**Comment by raelewis** [comment]
Fixes for these issues can be found in linked pull request.

- Fix Form Locks will be resolved with #58 , not this pull request.

**Comment by TAWinterton2** [comment]
Fixes merged. Closing issue
