### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by TechSolomon** [TAWinterton2/CS-F600-ML-GUI#86]
- [x] @raelewis 
    - [x] Photo
    - [x] Bio
- [x] @TAWinterton2 
    - [x] Photo
    - [x] Bio
- [ ] @jbonda 
    - [ ] Photo
    - [ ] Bio
- [x] @TechSolomon 
    - [x] Photo: https://avatars.githubusercontent.com/u/7608183
    - [x] Bio

**Comment by TAWinterton2** [comment]
added my bio and photo
